---
title: "possible_plots_fyh"
author: "Yihan Feng"
date: "11/15/2020"
output: html_document
---


```{r}
library(tidyverse)
library(plotly)
```


import data, and filter the year 2016 data
```{r}
hotel_df <- 
  read.csv("./data/hotel_bookings.csv", na = c("", "NA", "NULL")) %>%
  filter(arrival_date_year == "2016") %>%
  mutate(is_canceled = as.factor(is_canceled))
```



1. Lead time and cancellation
Need to change plot type. 

```{r}
lead_time_prop <- 
  hotel_df %>%
  mutate(is_canceled = recode(is_canceled, "1" = "Canceled", "0" = "Not Canceled")) %>%
  select(hotel, is_canceled, lead_time) %>%
  group_by(lead_time) %>%
  summarize(
    guest_total = n(),
    guest_canceled = sum(is_canceled == "Canceled")
  ) %>%
  mutate(
    prop_test = map2(.x = guest_canceled, .y = guest_total, ~prop.test(x = .x, n = .y)),
    tidy_test = map(.x = prop_test, ~broom::tidy(.x))
  ) %>%
  select(-prop_test) %>%
  unnest() %>%
  select(lead_time, estimate, conf.low, conf.high)
```

```{r}
lead_time_prop_plot <- 
  lead_time_prop %>%
  plot_ly(
    x = ~lead_time, y = ~estimate,
    type = "scatter", mode = "markers", colors = "viridis"
  ) %>%
  layout(title = "Cancellation Distribution with Lead Time",
         xaxis = list(title = "cancellation"),
         yaxis = list(title = "lead time (days)")
         )

lead_time_prop_plot
```



2. deposit type and cancellation

```{r}
# final version
deposit_df <- 
  hotel_df %>%
  mutate(is_canceled = recode(is_canceled, "1" = "Canceled", "0" = "Not Canceled")) %>%
  select(hotel, is_canceled, deposit_type)


deposit_prop <- 
  deposit_df %>%
  group_by(deposit_type, hotel) %>%
  summarize(
    guest_total = n(), 
    guest_canceled = sum(is_canceled == "Canceled")
  ) %>%
  mutate(
    prop_test = map2(.x = guest_canceled, .y = guest_total, ~prop.test(x = .x, n = .y)),
    tidy_test = map(.x = prop_test, ~broom::tidy(.x))
  ) %>%
  select(-prop_test) %>%
  unnest() %>%
  select(deposit_type, hotel, estimate, conf.low, conf.high)


deposit_prop_plot <- 
  deposit_prop %>%
    plot_ly(
    x = ~deposit_type, y = ~estimate, color = ~hotel,
    type = "bar", colors = "viridis"
  ) %>%
  layout(title = "Canceled Proportion with Deposit Type",
         xaxis = list(title = "Deposit Type"),
         yaxis = list(title = "Proportion of Cancellation"), 
         barmode = "group"
)

deposit_prop_plot
```



```{r}
# Deposit type & cancellation & resort hotel  
deposit_resort_prop <- 
  deposit_df %>%
  filter(hotel == "Resort Hotel") %>%
  group_by(deposit_type) %>%
  summarize(
    guest_total = n(), 
    guest_canceled = sum(is_canceled == "Canceled")
  ) %>%
  mutate(
    prop_test = map2(.x = guest_canceled, .y = guest_total, ~prop.test(x = .x, n = .y)),
    tidy_test = map(.x = prop_test, ~broom::tidy(.x))
  ) %>%
  select(-prop_test) %>%
  unnest() %>%
  select(deposit_type, estimate, conf.low, conf.high)
  
deposit_resort_prop_plot <- 
  deposit_resort_prop %>%
  plot_ly(
    x = ~deposit_type, y = ~estimate, color = ~deposit_type,
    type = "bar", colors = "viridis"
  ) %>%
  layout(title = "Resort Hotel Cancellation proportion with Deposit Type",
         xaxis = list(title = "Deposit Type"),
         yaxis = list(title = "Proportion of Cancellation")
)


# Deposit type & cancellation & city hotel  
deposit_city_prop <- 
  deposit_df %>%
  filter(hotel == "City Hotel") %>%
  group_by(deposit_type) %>%
  summarize(
    guest_total = n(), 
    guest_canceled = sum(is_canceled == "Canceled")
  ) %>%
  mutate(
    prop_test = map2(.x = guest_canceled, .y = guest_total, ~prop.test(x = .x, n = .y)),
    tidy_test = map(.x = prop_test, ~broom::tidy(.x))
  ) %>%
  select(-prop_test) %>%
  unnest() %>%
  select(deposit_type, estimate, conf.low, conf.high)
  
deposit_city_prop_plot <- 
  deposit_resort_prop %>%
  plot_ly(
    x = ~deposit_type, y = ~estimate, color = ~deposit_type,
    type = "bar", colors = "viridis"
  ) %>%
  layout(title = "City Hotel Cancellation proportion with Deposit Type",
         xaxis = list(title = "Deposit Type"),
         yaxis = list(title = "Proportion of Cancellation")
)
```




3. adult guests & cancellation
```{r}
hotel_df %>%
  count(is_canceled, adults) %>%
  mutate(is_canceled = recode(is_canceled, "1" = "Canceled", "0" = "Not Canceled"),
         text_label = str_c("Number of Adults: ", adults, "\nCounts: ", n)) %>%
  plot_ly(
    x = ~adults, y = ~n, color = ~is_canceled,
    type = "bar", text = ~text_label, colors = "viridis"
  ) %>% 
  layout(title = "Cancellation Distribution with Number of Adult Guests",
         xaxis = list(title = "Number of Adults"), 
         yaxis = list(title = "Counts"))
```


children only & cancellation

```{r}
hotel_df %>%
  select(is_canceled, adults, children) %>%
  filter(adults == 0, children > 0) %>%
  count(is_canceled, children) %>%
  mutate(
    is_canceled = recode(is_canceled, "1" = "Canceled", "0" = "Not Canceled"), 
    text_label = str_c("Number of Children: ", children, "\nTotal Counts: ", n)) %>%
  plot_ly(
    x = ~children, y = ~n, color = ~is_canceled, 
    type = "bar", text = ~text_label, colors = "viridis"
  ) %>%
  layout(title = "Cancellation Distribution with Number of Children Only", 
         xaxis = list(title = "Number of Children Only"), 
         yaxis = list(title = "Counts"))
```


4. special requests & cancellation

```{r}
hotel_df %>%
  select(is_canceled, total_of_special_requests, hotel) %>%
  count(total_of_special_requests, is_canceled) %>%
  mutate(is_canceled = recode(is_canceled, "1" = "Canceled", "0" = "Not Canceled"), 
         text_label = str_c("\nNumber of Special Requests: ", total_of_special_requests, "\nCounts: ", n)) %>%
  plot_ly(
    x = ~total_of_special_requests, y = ~n, color = ~is_canceled,
    type = "bar", text = ~text_label, colors = "viridis"
  ) %>%
  layout(
    title = "Cancellation Distribution with Number of Special Requests", 
    xaxis = list(title = "Total Number of Special Requests"), 
    yaxis = list(title = "Counts")
  )

```


```{r}
# final version
special_request_df <- 
  hotel_df %>%
  mutate(is_canceled = recode(is_canceled, "1" = "Canceled", "0" = "Not Canceled")) %>%
  select(hotel, is_canceled, total_of_special_requests)


special_request_prop <- 
  special_request_df %>%
  group_by(total_of_special_requests, hotel) %>%
  summarize(
    guest_total = n(), 
    guest_canceled = sum(is_canceled == "Canceled")
  ) %>%
  mutate(
    prop_test = map2(.x = guest_canceled, .y = guest_total, ~prop.test(x = .x, n = .y)),
    tidy_test = map(.x = prop_test, ~broom::tidy(.x))
  ) %>%
  select(-prop_test) %>%
  unnest() %>%
  select(total_of_special_requests, hotel, estimate, conf.low, conf.high)


special_request_prop_plot <- 
  special_request_prop %>%
    plot_ly(
    x = ~total_of_special_requests, y = ~estimate, color = ~hotel,
    type = "bar", colors = "viridis"
  ) %>%
  layout(title = "Canceled Proportion with Total Number of Special Request",
         xaxis = list(title = "Number of Special Requests"),
         yaxis = list(title = "Proportion of Cancellation"), 
         barmode = "group"
)

special_request_prop_plot
```


























