---
title: "Shiny Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
library(tidyverse)
library(flexdashboard)
library(shiny)
```

```{r}
hotel_df = 
  read.csv("./data/hotel_bookings.csv") %>% 
  mutate_if(is.character, as.factor)
  
```

Column {.sidebar}
-----------------------------------------------------------------------

```{r}
hotel_type = hotel_df %>% pull(hotel) %>% unique()

selectInput(
  "hotel_type",
  "Hotel Type",
  choices = c("Resort hotel", "City hotel")
)
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
# renderPlotly({
#   hotel_df %>%
#   select(arrival_date_month, is_canceled) %>%
#   mutate(arrival_date_month = as.factor(arrival_date_month),
#          is_canceled = as.factor(is_canceled)) %>%
#   count(arrival_date_month, is_canceled) %>%
#   mutate(arrival_date_month = fct_reorder(arrival_date_month, n)) %>%
#   plot_ly(x = ~arrival_date_month, y = ~ n, color = ~is_canceled, type ="bar", colors = "viridis")})
  
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}

```

### Chart C

```{r}

```

